; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28105.4 

	TITLE	C:\Users\lfish\Projects\WinViaCppQt\01-ErrorShow\GeneratedFiles\qrc_ErrorShow.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?qt_resource_data@@3QBEB DB 00H				; qt_resource_data
	DB	00H
	DB	02H
	DB	0feH
	DB	00H
	DB	00H
	DB	01H
	DB	00H
	DB	01H
	DB	00H
	DB	020H
	DB	020H
	DB	010H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	0e8H
	DB	02H
	DB	00H
	DB	00H
	DB	016H
	DB	00H
	DB	00H
	DB	00H
	DB	028H
	DB	00H
	DB	00H
	DB	00H
	DB	020H
	DB	00H
	DB	00H
	DB	00H
	DB	040H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	00H
	DB	04H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	080H
	DB	02H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	080H
	DB	00H
	DB	00H
	DB	080H
	DB	00H
	DB	00H
	DB	00H
	DB	080H
	DB	080H
	DB	00H
	DB	080H
	DB	00H
	DB	00H
	DB	00H
	DB	080H
	DB	00H
	DB	080H
	DB	00H
	DB	080H
	DB	080H
	DB	00H
	DB	00H
	DB	0c0H
	DB	0c0H
	DB	0c0H
	DB	00H
	DB	080H
	DB	080H
	DB	080H
	DB	00H
	DB	00H
	DB	00H
	DB	0ffH
	DB	00H
	DB	00H
	DB	0ffH
	DB	00H
	DB	00H
	DB	00H
	DB	0ffH
	DB	0ffH
	DB	00H
	DB	0ffH
	DB	00H
	DB	00H
	DB	00H
	DB	0ffH
	DB	00H
	DB	0ffH
	DB	00H
	DB	0ffH
	DB	0ffH
	DB	00H
	DB	00H
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	08H
	DB	088H
	DB	088H
	DB	088H
	DB	080H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	088H
	DB	088H
	DB	088H
	DB	088H
	DB	088H
	DB	088H
	DB	088H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	08H
	DB	081H
	DB	011H
	DB	011H
	DB	011H
	DB	018H
	DB	088H
	DB	088H
	DB	080H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	08H
	DB	011H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	011H
	DB	088H
	DB	088H
	DB	080H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	081H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	018H
	DB	088H
	DB	088H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	018H
	DB	088H
	DB	080H
	DB	00H
	DB	00H
	DB	00H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	088H
	DB	080H
	DB	00H
	DB	00H
	DB	01H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	018H
	DB	088H
	DB	00H
	DB	00H
	DB	01H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	018H
	DB	088H
	DB	080H
	DB	00H
	DB	019H
	DB	099H
	DB	099H
	DB	09fH
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	0f9H
	DB	099H
	DB	099H
	DB	091H
	DB	088H
	DB	080H
	DB	01H
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	099H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	018H
	DB	080H
	DB	01H
	DB	099H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	099H
	DB	018H
	DB	088H
	DB	01H
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	018H
	DB	088H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	088H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	088H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	088H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	088H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	088H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	088H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	080H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	080H
	DB	01H
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	018H
	DB	080H
	DB	01H
	DB	099H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	099H
	DB	018H
	DB	00H
	DB	01H
	DB	099H
	DB	099H
	DB	099H
	DB	0ffH
	DB	0f9H
	DB	099H
	DB	099H
	DB	099H
	DB	09fH
	DB	0ffH
	DB	099H
	DB	099H
	DB	099H
	DB	010H
	DB	00H
	DB	00H
	DB	019H
	DB	099H
	DB	099H
	DB	09fH
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	0f9H
	DB	099H
	DB	099H
	DB	091H
	DB	080H
	DB	00H
	DB	00H
	DB	01H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	018H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	010H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	010H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	099H
	DB	010H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	011H
	DB	019H
	DB	099H
	DB	099H
	DB	099H
	DB	091H
	DB	011H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	011H
	DB	011H
	DB	011H
	DB	010H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	0ffH
	DB	0f8H
	DB	07H
	DB	0ffH
	DB	0ffH
	DB	0c0H
	DB	00H
	DB	0ffH
	DB	0ffH
	DB	080H
	DB	00H
	DB	07fH
	DB	0feH
	DB	00H
	DB	00H
	DB	01fH
	DB	0fcH
	DB	00H
	DB	00H
	DB	0fH
	DB	0f8H
	DB	00H
	DB	00H
	DB	07H
	DB	0f0H
	DB	00H
	DB	00H
	DB	07H
	DB	0e0H
	DB	00H
	DB	00H
	DB	03H
	DB	0e0H
	DB	00H
	DB	00H
	DB	01H
	DB	0c0H
	DB	00H
	DB	00H
	DB	01H
	DB	080H
	DB	00H
	DB	00H
	DB	01H
	DB	080H
	DB	00H
	DB	00H
	DB	00H
	DB	080H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	080H
	DB	00H
	DB	00H
	DB	01H
	DB	080H
	DB	00H
	DB	00H
	DB	03H
	DB	080H
	DB	00H
	DB	00H
	DB	07H
	DB	0c0H
	DB	00H
	DB	00H
	DB	07H
	DB	0e0H
	DB	00H
	DB	00H
	DB	0fH
	DB	0e0H
	DB	00H
	DB	00H
	DB	01fH
	DB	0f0H
	DB	00H
	DB	00H
	DB	03fH
	DB	0f8H
	DB	00H
	DB	00H
	DB	07fH
	DB	0feH
	DB	00H
	DB	01H
	DB	0ffH
	DB	0ffH
	DB	00H
	DB	03H
	DB	0ffH
	DB	0ffH
	DB	0e0H
	DB	01fH
	DB	0ffH
	ORG $+2
?qt_resource_name@@3QBEB DB 00H				; qt_resource_name
	DB	0dH
	DB	06H
	DB	05cH
	DB	081H
	DB	09fH
	DB	00H
	DB	045H
	DB	00H
	DB	072H
	DB	00H
	DB	072H
	DB	00H
	DB	06fH
	DB	00H
	DB	072H
	DB	00H
	DB	053H
	DB	00H
	DB	068H
	DB	00H
	DB	06fH
	DB	00H
	DB	077H
	DB	00H
	DB	02eH
	DB	00H
	DB	069H
	DB	00H
	DB	063H
	DB	00H
	DB	06fH
?qt_resource_struct@@3QBEB DB 00H			; qt_resource_struct
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	02H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	016H
	DB	05cH
	DB	0cdH
	DB	088H
	DB	090H
CONST	ENDS
PUBLIC	?qInitResources_ErrorShow@@YAHXZ		; qInitResources_ErrorShow
PUBLIC	?qCleanupResources_ErrorShow@@YAHXZ		; qCleanupResources_ErrorShow
EXTRN	_atexit:PROC
EXTRN	?qRegisterResourceData@@YA_NHPBE00@Z:PROC	; qRegisterResourceData
EXTRN	?qUnregisterResourceData@@YA_NHPBE00@Z:PROC	; qUnregisterResourceData
EXTRN	@__security_check_cookie@4:PROC
EXTRN	___CxxFrameHandler3:PROC
EXTRN	___security_cookie:DWORD
_BSS	SEGMENT
?dummy@?A0x8c1c2825@@3Uinitializer@1@A DB 01H DUP (?)	; `anonymous namespace'::dummy
_BSS	ENDS
CRT$XCU	SEGMENT
?dummy$initializer$@?A0x8c1c2825@@3P6AXXZA DD FLAT:??__Edummy@?A0x8c1c2825@@YAXXZ ; `anonymous namespace'::dummy$initializer$
CRT$XCU	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??1initializer@?A0x8c1c2825@@QAE@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__Fdummy@?A0x8c1c2825@@YAXXZ
text$yd	SEGMENT
??__Fdummy@?A0x8c1c2825@@YAXXZ PROC			; `anonymous namespace'::`dynamic atexit destructor for 'dummy'', COMDAT
	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET ?dummy@?A0x8c1c2825@@3Uinitializer@1@A ; `anonymous namespace'::dummy
	call	??1initializer@?A0x8c1c2825@@QAE@XZ	; `anonymous namespace'::initializer::~initializer
	pop	ebp
	ret	0
??__Fdummy@?A0x8c1c2825@@YAXXZ ENDP			; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
text$yd	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__Edummy@?A0x8c1c2825@@YAXXZ
text$di	SEGMENT
??__Edummy@?A0x8c1c2825@@YAXXZ PROC			; `anonymous namespace'::`dynamic initializer for 'dummy'', COMDAT
; File C:\Users\lfish\Projects\WinViaCppQt\01-ErrorShow\GeneratedFiles\qrc_ErrorShow.cpp
; Line 128
	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET ?dummy@?A0x8c1c2825@@3Uinitializer@1@A ; `anonymous namespace'::dummy
	call	??0initializer@?A0x8c1c2825@@QAE@XZ	; `anonymous namespace'::initializer::initializer
	push	OFFSET ??__Fdummy@?A0x8c1c2825@@YAXXZ	; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
	call	_atexit
	add	esp, 4
	pop	ebp
	ret	0
??__Edummy@?A0x8c1c2825@@YAXXZ ENDP			; `anonymous namespace'::`dynamic initializer for 'dummy''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1initializer@?A0x8c1c2825@@QAE@XZ
_TEXT	SEGMENT
_this$ = -16						; size = 4
__$EHRec$ = -12						; size = 12
??1initializer@?A0x8c1c2825@@QAE@XZ PROC		; `anonymous namespace'::initializer::~initializer, COMDAT
; _this$ = ecx
; File C:\Users\lfish\Projects\WinViaCppQt\01-ErrorShow\GeneratedFiles\qrc_ErrorShow.cpp
; Line 127
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??1initializer@?A0x8c1c2825@@QAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	push	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	call	?qCleanupResources_ErrorShow@@YAHXZ	; qCleanupResources_ErrorShow
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$??1initializer@?A0x8c1c2825@@QAE@XZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-8]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??1initializer@?A0x8c1c2825@@QAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1initializer@?A0x8c1c2825@@QAE@XZ ENDP		; `anonymous namespace'::initializer::~initializer
; Function compile flags: /Odtp
;	COMDAT ??0initializer@?A0x8c1c2825@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0initializer@?A0x8c1c2825@@QAE@XZ PROC		; `anonymous namespace'::initializer::initializer, COMDAT
; _this$ = ecx
; File C:\Users\lfish\Projects\WinViaCppQt\01-ErrorShow\GeneratedFiles\qrc_ErrorShow.cpp
; Line 126
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	call	?qInitResources_ErrorShow@@YAHXZ	; qInitResources_ErrorShow
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0initializer@?A0x8c1c2825@@QAE@XZ ENDP		; `anonymous namespace'::initializer::initializer
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_version$ = -4						; size = 4
?qCleanupResources_ErrorShow@@YAHXZ PROC		; qCleanupResources_ErrorShow
; File C:\Users\lfish\Projects\WinViaCppQt\01-ErrorShow\GeneratedFiles\qrc_ErrorShow.cpp
; Line 117
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 118
	mov	DWORD PTR _version$[ebp], 3
; Line 119
	push	OFFSET ?qt_resource_data@@3QBEB
	push	OFFSET ?qt_resource_name@@3QBEB
	push	OFFSET ?qt_resource_struct@@3QBEB
	mov	eax, DWORD PTR _version$[ebp]
	push	eax
	call	?qUnregisterResourceData@@YA_NHPBE00@Z	; qUnregisterResourceData
	add	esp, 16					; 00000010H
; Line 121
	mov	eax, 1
; Line 122
	mov	esp, ebp
	pop	ebp
	ret	0
?qCleanupResources_ErrorShow@@YAHXZ ENDP		; qCleanupResources_ErrorShow
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_version$ = -4						; size = 4
?qInitResources_ErrorShow@@YAHXZ PROC			; qInitResources_ErrorShow
; File C:\Users\lfish\Projects\WinViaCppQt\01-ErrorShow\GeneratedFiles\qrc_ErrorShow.cpp
; Line 108
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 109
	mov	DWORD PTR _version$[ebp], 3
; Line 110
	push	OFFSET ?qt_resource_data@@3QBEB
	push	OFFSET ?qt_resource_name@@3QBEB
	push	OFFSET ?qt_resource_struct@@3QBEB
	mov	eax, DWORD PTR _version$[ebp]
	push	eax
	call	?qRegisterResourceData@@YA_NHPBE00@Z	; qRegisterResourceData
	add	esp, 16					; 00000010H
; Line 112
	mov	eax, 1
; Line 113
	mov	esp, ebp
	pop	ebp
	ret	0
?qInitResources_ErrorShow@@YAHXZ ENDP			; qInitResources_ErrorShow
_TEXT	ENDS
END
