; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28105.4 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG230370 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qmetaty'
	DB	'pe.h', 00H
$SG219861 DB	00H
	ORG $+2
$SG230371 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG230372 DB	'qRegisterNormalizedMetaType', 00H
$SG235245 DB	'%s', 00H
	ORG $+1
$SG233343 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG233344 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG233345 DB	'qRegisterNormalizedMetaType', 00H
$SG219875 DB	00H, 00H
	ORG $+2
$SG233682 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG233683 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG233684 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG234021 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG234022 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG234023 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG234895 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG234896 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG234897 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG235244 DB	'invalid argument', 00H
	ORG $+15
$SG235246 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Ente'
	DB	'rprise\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+7
$SG235247 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'E', 00H, 'n', 00H, 't', 00H, 'e', 00H, 'r', 00H, 'p', 00H
	DB	'r', 00H, 'i', 00H, 's', 00H, 'e', 00H, '\', 00H, 'V', 00H, 'C'
	DB	00H, '\', 00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H
	DB	'\', 00H, 'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1'
	DB	00H, '4', 00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H
	DB	'8', 00H, '1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n'
	DB	00H, 'c', 00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H
	DB	'x', 00H, 'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y'
	DB	00H, 00H, 00H
	ORG $+14
$SG235248 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG235249 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+10
$SG235360 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Ente'
	DB	'rprise\VC\Tools\MSVC\14.23.28105\include\xlocale', 00H
	ORG $+7
?qt_meta_stringdata_Singleton@@3Uqt_meta_stringdata_Singleton_t@@B DD 0ffffffffH ; qt_meta_stringdata_Singleton
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000018H
	DB	053H
	DB	069H
	DB	06eH
	DB	067H
	DB	06cH
	DB	065H
	DB	074H
	DB	06fH
	DB	06eH
	DB	00H
	ORG $+6
?qt_meta_data_Singleton@@3QBIB DD 08H			; qt_meta_data_Singleton
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Singleton@@UEBAPEBUQMetaObject@@XZ	; Singleton::metaObject
PUBLIC	?qt_metacast@Singleton@@UEAAPEAXPEBD@Z		; Singleton::qt_metacast
PUBLIC	?qt_metacall@Singleton@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; Singleton::qt_metacall
PUBLIC	?qt_static_metacall@Singleton@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Singleton::qt_static_metacall
PUBLIC	?staticMetaObject@Singleton@@2UQMetaObject@@B	; Singleton::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@Singleton@@2UQMetaObject@@B DB 030H DUP (?) ; Singleton::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@Singleton@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN6
	DD	imagerel $LN6+88
	DD	imagerel $unwind$?metaObject@Singleton@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@Singleton@@UEAAPEAXPEBD@Z DD imagerel $LN8
	DD	imagerel $LN8+75
	DD	imagerel $unwind$?qt_metacast@Singleton@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@Singleton@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN4
	DD	imagerel $LN4+61
	DD	imagerel $unwind$?qt_metacall@Singleton@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Singleton@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@Singleton@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Singleton@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@Singleton@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@Singleton@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@Singleton@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Singleton@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Singleton@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Singleton::staticMetaObject'', COMDAT
; File C:\Users\lfish\Projects\WinViaCppStudy\03-Singleton\03-Singleton\GeneratedFiles\Debug\moc_Singleton.cpp
; Line 67
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@Singleton@@2UQMetaObject@@B, rax
; Line 68
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_Singleton@@3Uqt_meta_stringdata_Singleton_t@@B
	mov	QWORD PTR ?staticMetaObject@Singleton@@2UQMetaObject@@B+8, rax
; Line 69
	lea	rax, OFFSET FLAT:?qt_meta_data_Singleton@@3QBIB
	mov	QWORD PTR ?staticMetaObject@Singleton@@2UQMetaObject@@B+16, rax
; Line 70
	lea	rax, OFFSET FLAT:?qt_static_metacall@Singleton@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Singleton::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@Singleton@@2UQMetaObject@@B+24, rax
; Line 71
	mov	QWORD PTR ?staticMetaObject@Singleton@@2UQMetaObject@@B+32, 0
; Line 72
	mov	QWORD PTR ?staticMetaObject@Singleton@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@Singleton@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Singleton::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@Singleton@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; Singleton::qt_static_metacall
; File C:\Users\lfish\Projects\WinViaCppStudy\03-Singleton\03-Singleton\GeneratedFiles\Debug\moc_Singleton.cpp
; Line 59
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 64
	ret	0
?qt_static_metacall@Singleton@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Singleton::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@Singleton@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; Singleton::qt_metacall
; File C:\Users\lfish\Projects\WinViaCppStudy\03-Singleton\03-Singleton\GeneratedFiles\Debug\moc_Singleton.cpp
; Line 90
$LN4:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 91
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 92
	mov	eax, DWORD PTR _id$[rsp]
; Line 93
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@Singleton@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Singleton::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@Singleton@@UEAAPEAXPEBD@Z PROC		; Singleton::qt_metacast
; File C:\Users\lfish\Projects\WinViaCppStudy\03-Singleton\03-Singleton\GeneratedFiles\Debug\moc_Singleton.cpp
; Line 82
$LN8:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 83
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 84
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_Singleton@@3Uqt_meta_stringdata_Singleton_t@@B+24
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 85
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 86
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 87
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@Singleton@@UEAAPEAXPEBD@Z ENDP		; Singleton::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@Singleton@@UEBAPEBUQMetaObject@@XZ PROC	; Singleton::metaObject
; File C:\Users\lfish\Projects\WinViaCppStudy\03-Singleton\03-Singleton\GeneratedFiles\Debug\moc_Singleton.cpp
; Line 77
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 78
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@Singleton@@2UQMetaObject@@B ; Singleton::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 79
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@Singleton@@UEBAPEBUQMetaObject@@XZ ENDP	; Singleton::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File C:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\lfish\Projects\WinViaCppStudy\03-Singleton\03-Singleton\GeneratedFiles\Debug\moc_Singleton.cpp
; Line 96
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\lfish\Projects\WinViaCppStudy\03-Singleton\03-Singleton\GeneratedFiles\Debug\moc_Singleton.cpp
; Line 96
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
