; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28105.4 

	TITLE	C:\Users\lfish\Projects\WinViaCppStudy\17-FileRev\17-FileRev\Debug\moc\moc_FileRev.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG229450 DB	'invalid argument', 00H
	ORG $+3
$SG229451 DB	'%s', 00H
	ORG $+1
$SG229452 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Ente'
	DB	'rprise\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+7
$SG229453 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'E', 00H, 'n', 00H, 't', 00H, 'e', 00H, 'r', 00H, 'p', 00H
	DB	'r', 00H, 'i', 00H, 's', 00H, 'e', 00H, '\', 00H, 'V', 00H, 'C'
	DB	00H, '\', 00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H
	DB	'\', 00H, 'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1'
	DB	00H, '4', 00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H
	DB	'8', 00H, '1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n'
	DB	00H, 'c', 00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H
	DB	'x', 00H, 'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y'
	DB	00H, 00H, 00H
	ORG $+6
$SG229454 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG229455 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG229566 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Ente'
	DB	'rprise\VC\Tools\MSVC\14.23.28105\include\xlocale', 00H
	ORG $+3
?qt_meta_stringdata_FileRev@@3Uqt_meta_stringdata_FileRev_t@@B DD 0ffffffffH ; qt_meta_stringdata_FileRev
	DD	07H
	DD	00H
	DD	010H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	052H
	DB	065H
	DB	076H
	DB	00H
?qt_meta_data_FileRev@@3QBIB DD 08H			; qt_meta_data_FileRev
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
$SG224256 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017\include\QtCore\qmetatype.'
	DB	'h', 00H
	ORG $+6
$SG224257 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG224258 DB	'qRegisterNormalizedMetaType', 00H
$SG227210 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017\include\QtCore\qmetatype.'
	DB	'h', 00H
	ORG $+2
$SG227211 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG227212 DB	'qRegisterNormalizedMetaType', 00H
$SG227549 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017\include\QtCore\qmetatype.'
	DB	'h', 00H
	ORG $+2
$SG227550 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG227551 DB	'qRegisterNormalizedMetaType', 00H
$SG227888 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017\include\QtCore\qmetatype.'
	DB	'h', 00H
	ORG $+2
$SG227889 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG227890 DB	'qRegisterNormalizedMetaType', 00H
$SG228227 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017\include\QtCore\qmetatype.'
	DB	'h', 00H
	ORG $+2
$SG228228 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG228229 DB	'qRegisterNormalizedMetaType', 00H
$SG229101 DB	'C:\Qt\Qt5.13.0\5.13.0\msvc2017\include\QtCore\qmetatype.'
	DB	'h', 00H
	ORG $+2
$SG229102 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG229103 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@FileRev@@UBEPBUQMetaObject@@XZ	; FileRev::metaObject
PUBLIC	?qt_metacast@FileRev@@UAEPAXPBD@Z		; FileRev::qt_metacast
PUBLIC	?qt_metacall@FileRev@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; FileRev::qt_metacall
PUBLIC	?qt_static_metacall@FileRev@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; FileRev::qt_static_metacall
PUBLIC	?staticMetaObject@FileRev@@2UQMetaObject@@B	; FileRev::staticMetaObject
EXTRN	_strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@FileRev@@2UQMetaObject@@B DB 018H DUP (?) ; FileRev::staticMetaObject
_BSS	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@FileRev@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@FileRev@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@FileRev@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@FileRev@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@FileRev@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'FileRev::staticMetaObject'', COMDAT
; File C:\Users\lfish\Projects\WinViaCppStudy\17-FileRev\17-FileRev\Debug\moc\moc_FileRev.cpp
; Line 73
	push	ebp
	mov	ebp, esp
; Line 67
	mov	eax, DWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@FileRev@@2UQMetaObject@@B, eax
; Line 68
	mov	DWORD PTR ?staticMetaObject@FileRev@@2UQMetaObject@@B+4, OFFSET ?qt_meta_stringdata_FileRev@@3Uqt_meta_stringdata_FileRev_t@@B
; Line 69
	mov	DWORD PTR ?staticMetaObject@FileRev@@2UQMetaObject@@B+8, OFFSET ?qt_meta_data_FileRev@@3QBIB
; Line 70
	mov	DWORD PTR ?staticMetaObject@FileRev@@2UQMetaObject@@B+12, OFFSET ?qt_static_metacall@FileRev@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; FileRev::qt_static_metacall
; Line 71
	mov	DWORD PTR ?staticMetaObject@FileRev@@2UQMetaObject@@B+16, 0
; Line 72
	mov	DWORD PTR ?staticMetaObject@FileRev@@2UQMetaObject@@B+20, 0
	pop	ebp
	ret	0
??__E?staticMetaObject@FileRev@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'FileRev::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@FileRev@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; FileRev::qt_static_metacall
; File C:\Users\lfish\Projects\WinViaCppStudy\17-FileRev\17-FileRev\Debug\moc\moc_FileRev.cpp
; Line 59
	push	ebp
	mov	ebp, esp
; Line 64
	pop	ebp
	ret	0
?qt_static_metacall@FileRev@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; FileRev::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@FileRev@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; FileRev::qt_metacall
; _this$ = ecx
; File C:\Users\lfish\Projects\WinViaCppStudy\17-FileRev\17-FileRev\Debug\moc\moc_FileRev.cpp
; Line 90
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 91
	mov	eax, DWORD PTR __a$[ebp]
	push	eax
	mov	ecx, DWORD PTR __id$[ebp]
	push	ecx
	mov	edx, DWORD PTR __c$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacall@QWidget@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	DWORD PTR __id$[ebp], eax
; Line 92
	mov	eax, DWORD PTR __id$[ebp]
; Line 93
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@FileRev@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; FileRev::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__clname$ = 8						; size = 4
?qt_metacast@FileRev@@UAEPAXPBD@Z PROC			; FileRev::qt_metacast
; _this$ = ecx
; File C:\Users\lfish\Projects\WinViaCppStudy\17-FileRev\17-FileRev\Debug\moc\moc_FileRev.cpp
; Line 82
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 83
	cmp	DWORD PTR __clname$[ebp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 84
	push	OFFSET ?qt_meta_stringdata_FileRev@@3Uqt_meta_stringdata_FileRev_t@@B+16
	mov	eax, DWORD PTR __clname$[ebp]
	push	eax
	call	_strcmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 85
	mov	eax, DWORD PTR _this$[ebp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 86
	mov	ecx, DWORD PTR __clname$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacast@QWidget@@UAEPAXPBD@Z
$LN1@qt_metacas:
; Line 87
	mov	esp, ebp
	pop	ebp
	ret	4
?qt_metacast@FileRev@@UAEPAXPBD@Z ENDP			; FileRev::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = -8						; size = 4
_this$ = -4						; size = 4
?metaObject@FileRev@@UBEPBUQMetaObject@@XZ PROC		; FileRev::metaObject
; _this$ = ecx
; File C:\Users\lfish\Projects\WinViaCppStudy\17-FileRev\17-FileRev\Debug\moc\moc_FileRev.cpp
; Line 77
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx
; Line 78
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	DWORD PTR [eax+24], 0
	je	SHORT $LN3@metaObject
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	ecx, eax
	call	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
	mov	DWORD PTR tv82[ebp], eax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	mov	DWORD PTR tv82[ebp], OFFSET ?staticMetaObject@FileRev@@2UQMetaObject@@B ; FileRev::staticMetaObject
$LN4@metaObject:
	mov	eax, DWORD PTR tv82[ebp]
; Line 79
	mov	esp, ebp
	pop	ebp
	ret	0
?metaObject@FileRev@@UBEPBUQMetaObject@@XZ ENDP		; FileRev::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File C:\Qt\Qt5.13.0\5.13.0\msvc2017\include\QtCore\qscopedpointer.h
; Line 117
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 118
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
; Line 119
	mov	esp, ebp
	pop	ebp
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\lfish\Projects\WinViaCppStudy\17-FileRev\17-FileRev\Debug\moc\moc_FileRev.cpp
; Line 96
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\lfish\Projects\WinViaCppStudy\17-FileRev\17-FileRev\Debug\moc\moc_FileRev.cpp
; Line 96
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
